<?php
	if(!defined("SYSTEM_2")) exit;
	function Sifrele($metin)
	{
		$metin = base64_encode($metin);
		$metin = str_replace("0", "-|000-", $metin);
		$metin = str_replace("1", "-|111-", $metin);
		$metin = str_replace("2", "-|222-", $metin);
		$metin = str_replace("3", "-|333-", $metin);
		$metin = str_replace("4", "-|444-", $metin);
		$metin = str_replace("5", "-|555-", $metin);
		$metin = str_replace("6", "-|666-", $metin);
		$metin = str_replace("7", "-|777-", $metin);
		$metin = str_replace("8", "-|888-", $metin);
		$metin = str_replace("9", "-|999-", $metin);

		$metin = str_replace("q", "-|99-", $metin);
		$metin = str_replace("Q", "-|1-", $metin);
		$metin = str_replace("w", "-|98-", $metin);
		$metin = str_replace("W", "-|2-", $metin);
		$metin = str_replace("e", "-|97-", $metin);
		$metin = str_replace("E", "-|3-", $metin);
		$metin = str_replace("r", "-|96-", $metin);
		$metin = str_replace("R", "-|4-", $metin);
		$metin = str_replace("y", "-|95-", $metin);
		$metin = str_replace("Y", "-|5-", $metin);
		$metin = str_replace("u", "-|94-", $metin);
		$metin = str_replace("U", "-|6-", $metin);
		$metin = str_replace("ı", "-|93-", $metin);
		$metin = str_replace("I", "-|7-", $metin);
		$metin = str_replace("o", "-|92-", $metin);
		$metin = str_replace("O", "-|8-", $metin);
		$metin = str_replace("p", "-|91-", $metin);
		$metin = str_replace("P", "-|9-", $metin);
		$metin = str_replace("ğ", "-|90-", $metin);
		$metin = str_replace("Ğ", "-|10-", $metin);
		$metin = str_replace("ü", "-|89-", $metin);
		$metin = str_replace("Ü", "-|11-", $metin);
		$metin = str_replace("a", "-|88-", $metin);
		$metin = str_replace("A", "-|12-", $metin);
		$metin = str_replace("b", "-|87-", $metin);
		$metin = str_replace("B", "-|13-", $metin);
		$metin = str_replace("c", "-|86-", $metin);
		$metin = str_replace("C", "-|14-", $metin);
		$metin = str_replace("d", "-|85-", $metin);
		$metin = str_replace("D", "-|15-", $metin);
		$metin = str_replace("f", "-|84-", $metin);
		$metin = str_replace("F", "-|16-", $metin);
		$metin = str_replace("g", "-|83-", $metin);
		$metin = str_replace("G", "-|17-", $metin);
		$metin = str_replace("h", "-|82-", $metin);
		$metin = str_replace("H", "-|18-", $metin);
		$metin = str_replace("j", "-|81-", $metin);
		$metin = str_replace("J", "-|19-", $metin);
		$metin = str_replace("k", "-|80-", $metin);
		$metin = str_replace("K", "-|20-", $metin);
		$metin = str_replace("l", "-|79-", $metin);
		$metin = str_replace("L", "-|21-", $metin);
		$metin = str_replace("ş", "-|78-", $metin);
		$metin = str_replace("Ş", "-|22-", $metin);
		$metin = str_replace("i", "-|77-", $metin);
		$metin = str_replace("İ", "-|23-", $metin);
		$metin = str_replace("z", "-|76-", $metin);
		$metin = str_replace("Z", "-|24-", $metin);
		$metin = str_replace("x", "-|75-", $metin);
		$metin = str_replace("X", "-|25-", $metin);
		$metin = str_replace("c", "-|74-", $metin);
		$metin = str_replace("C", "-|26-", $metin);
		$metin = str_replace("v", "-|73-", $metin);
		$metin = str_replace("V", "-|27-", $metin);
		$metin = str_replace("b", "-|72-", $metin);
		$metin = str_replace("B", "-|28-", $metin);
		$metin = str_replace("n", "-|71-", $metin);
		$metin = str_replace("N", "-|29-", $metin);
		$metin = str_replace("m", "-|70-", $metin);
		$metin = str_replace("M", "-|30-", $metin);
		$metin = str_replace("ö", "-|69-", $metin);
		$metin = str_replace("Ö", "-|31-", $metin);
		$metin = str_replace("ç", "-|68-", $metin);
		$metin = str_replace("Ç", "-|32-", $metin);
		$metin = str_replace("t", "-|67-", $metin);
		$metin = str_replace("T", "-|33-", $metin);
		$metin = str_replace("s", "-|66-", $metin);
		$metin = str_replace("S", "-|34-", $metin);
		return $metin;
	}

	function SifreCoz($metin)
    {
		$metin = replaceyap($metin, "0", "-|000-");
		$metin = replaceyap($metin, "1", "-|111-");
		$metin = replaceyap($metin, "2", "-|222-");
		$metin = replaceyap($metin, "3", "-|333-");
		$metin = replaceyap($metin, "4", "-|444-");
		$metin = replaceyap($metin, "5", "-|555-");
		$metin = replaceyap($metin, "6", "-|666-");
		$metin = replaceyap($metin, "7", "-|777-");
		$metin = replaceyap($metin, "8", "-|888-");
		$metin = replaceyap($metin, "9", "-|999-");

		$metin = replaceyap($metin, "q", "-|99-");
		$metin = replaceyap($metin, "Q", "-|1-");
		$metin = replaceyap($metin, "w", "-|98-");
		$metin = replaceyap($metin, "W", "-|2-");
		$metin = replaceyap($metin, "e", "-|97-");
		$metin = replaceyap($metin, "E", "-|3-");
		$metin = replaceyap($metin, "r", "-|96-");
		$metin = replaceyap($metin, "R", "-|4-");
		$metin = replaceyap($metin, "y", "-|95-");
		$metin = replaceyap($metin, "Y", "-|5-");
		$metin = replaceyap($metin, "u", "-|94-");
		$metin = replaceyap($metin, "U", "-|6-");
		$metin = replaceyap($metin, "ı", "-|93-");
		$metin = replaceyap($metin, "I", "-|7-");
		$metin = replaceyap($metin, "o", "-|92-");
		$metin = replaceyap($metin, "O", "-|8-");
		$metin = replaceyap($metin, "p", "-|91-");
		$metin = replaceyap($metin, "P", "-|9-");
		$metin = replaceyap($metin, "ğ", "-|90-");
		$metin = replaceyap($metin, "Ğ", "-|10-");
		$metin = replaceyap($metin, "ü", "-|89-");
		$metin = replaceyap($metin, "Ü", "-|11-");
		$metin = replaceyap($metin, "a", "-|88-");
		$metin = replaceyap($metin, "A", "-|12-");
		$metin = replaceyap($metin, "b", "-|87-");
		$metin = replaceyap($metin, "B", "-|13-");
		$metin = replaceyap($metin, "c", "-|86-");
		$metin = replaceyap($metin, "C", "-|14-");
		$metin = replaceyap($metin, "d", "-|85-");
		$metin = replaceyap($metin, "D", "-|15-");
		$metin = replaceyap($metin, "f", "-|84-");
		$metin = replaceyap($metin, "F", "-|16-");
		$metin = replaceyap($metin, "g", "-|83-");
		$metin = replaceyap($metin, "G", "-|17-");
		$metin = replaceyap($metin, "h", "-|82-");
		$metin = replaceyap($metin, "H", "-|18-");
		$metin = replaceyap($metin, "j", "-|81-");
		$metin = replaceyap($metin, "J", "-|19-");
		$metin = replaceyap($metin, "k", "-|80-");
		$metin = replaceyap($metin, "K", "-|20-");
		$metin = replaceyap($metin, "l", "-|79-");
		$metin = replaceyap($metin, "L", "-|21-");
		$metin = replaceyap($metin, "ş", "-|78-");
		$metin = replaceyap($metin, "Ş", "-|22-");
		$metin = replaceyap($metin, "i", "-|77-");
		$metin = replaceyap($metin, "İ", "-|23-");
		$metin = replaceyap($metin, "z", "-|76-");
		$metin = replaceyap($metin, "Z", "-|24-");
		$metin = replaceyap($metin, "x", "-|75-");
		$metin = replaceyap($metin, "X", "-|25-");
		$metin = replaceyap($metin, "c", "-|74-");
		$metin = replaceyap($metin, "C", "-|26-");
		$metin = replaceyap($metin, "v", "-|73-");
		$metin = replaceyap($metin, "V", "-|27-");
		$metin = replaceyap($metin, "b", "-|72-");
		$metin = replaceyap($metin, "B", "-|28-");
		$metin = replaceyap($metin, "n", "-|71-");
		$metin = replaceyap($metin, "N", "-|29-");
		$metin = replaceyap($metin, "m", "-|70-");
		$metin = replaceyap($metin, "M", "-|30-");
		$metin = replaceyap($metin, "ö", "-|69-");
		$metin = replaceyap($metin, "Ö", "-|31-");
		$metin = replaceyap($metin, "ç", "-|68-");
		$metin = replaceyap($metin, "Ç", "-|32-");
		$metin = replaceyap($metin, "t", "-|67-");
		$metin = replaceyap($metin, "T", "-|33-");
		$metin = replaceyap($metin, "s", "-|66-");
		$metin = replaceyap($metin, "S", "-|34-");
		return base64_decode($metin);
	}

	function replaceyap($metin, $metin2, $metin3)
	{
		$metin = str_replace($metin3, $metin2, $metin);
		return $metin;
	}
?>